//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace ServicelinkASAPMobile.com.servicelinkasap.wise.staging {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FieldServiceSoap", Namespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx")]
    public partial class FieldService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateDeviceOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSignatureOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPostingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePostingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddDeviceTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendPushAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgentOrDelegateByOrderIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmCanXPPTOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateHoldOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FieldService() {
            this.Url = global::ServicelinkASAPMobile.Properties.Settings.Default.ServicelinkASAPMobile_com_servicelinkasap_wise_staging_FieldService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event AuthenticateUserCompletedEventHandler AuthenticateUserCompleted;
        
        /// <remarks/>
        public event AuthenticateDeviceCompletedEventHandler AuthenticateDeviceCompleted;
        
        /// <remarks/>
        public event UpdateSignatureCompletedEventHandler UpdateSignatureCompleted;
        
        /// <remarks/>
        public event GetPostingsCompletedEventHandler GetPostingsCompleted;
        
        /// <remarks/>
        public event UpdatePostingsCompletedEventHandler UpdatePostingsCompleted;
        
        /// <remarks/>
        public event AddDeviceTokenCompletedEventHandler AddDeviceTokenCompleted;
        
        /// <remarks/>
        public event SendPushAlertCompletedEventHandler SendPushAlertCompleted;
        
        /// <remarks/>
        public event GetAgentOrDelegateByOrderIdCompletedEventHandler GetAgentOrDelegateByOrderIdCompleted;
        
        /// <remarks/>
        public event GetOrderByIdCompletedEventHandler GetOrderByIdCompleted;
        
        /// <remarks/>
        public event GetSalesCompletedEventHandler GetSalesCompleted;
        
        /// <remarks/>
        public event UpdateSalesCompletedEventHandler UpdateSalesCompleted;
        
        /// <remarks/>
        public event ConfirmCanXPPTCompletedEventHandler ConfirmCanXPPTCompleted;
        
        /// <remarks/>
        public event UpdateHoldCompletedEventHandler UpdateHoldCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/Ping", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/Authenti" +
            "cateUser", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] AuthenticateUser(AuthenticationHeader authHeader) {
            object[] results = this.Invoke("AuthenticateUser", new object[] {
                        authHeader});
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(AuthenticationHeader authHeader) {
            this.AuthenticateUserAsync(authHeader, null);
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(AuthenticationHeader authHeader, object userState) {
            if ((this.AuthenticateUserOperationCompleted == null)) {
                this.AuthenticateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserOperationCompleted);
            }
            this.InvokeAsync("AuthenticateUser", new object[] {
                        authHeader}, this.AuthenticateUserOperationCompleted, userState);
        }
        
        private void OnAuthenticateUserOperationCompleted(object arg) {
            if ((this.AuthenticateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/Authenti" +
            "cateDevice", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AuthenticateDevice(AuthenticationHeader authHeader) {
            object[] results = this.Invoke("AuthenticateDevice", new object[] {
                        authHeader});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateDeviceAsync(AuthenticationHeader authHeader) {
            this.AuthenticateDeviceAsync(authHeader, null);
        }
        
        /// <remarks/>
        public void AuthenticateDeviceAsync(AuthenticationHeader authHeader, object userState) {
            if ((this.AuthenticateDeviceOperationCompleted == null)) {
                this.AuthenticateDeviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateDeviceOperationCompleted);
            }
            this.InvokeAsync("AuthenticateDevice", new object[] {
                        authHeader}, this.AuthenticateDeviceOperationCompleted, userState);
        }
        
        private void OnAuthenticateDeviceOperationCompleted(object arg) {
            if ((this.AuthenticateDeviceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateDeviceCompleted(this, new AuthenticateDeviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/UpdateSi" +
            "gnature", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateSignature(AuthenticationHeader authHeader, Signature signature) {
            object[] results = this.Invoke("UpdateSignature", new object[] {
                        authHeader,
                        signature});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSignatureAsync(AuthenticationHeader authHeader, Signature signature) {
            this.UpdateSignatureAsync(authHeader, signature, null);
        }
        
        /// <remarks/>
        public void UpdateSignatureAsync(AuthenticationHeader authHeader, Signature signature, object userState) {
            if ((this.UpdateSignatureOperationCompleted == null)) {
                this.UpdateSignatureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSignatureOperationCompleted);
            }
            this.InvokeAsync("UpdateSignature", new object[] {
                        authHeader,
                        signature}, this.UpdateSignatureOperationCompleted, userState);
        }
        
        private void OnUpdateSignatureOperationCompleted(object arg) {
            if ((this.UpdateSignatureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSignatureCompleted(this, new UpdateSignatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/GetPosti" +
            "ngs", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Posting[] GetPostings(AuthenticationHeader authHeader, bool myDay, System.DateTime startDate, System.DateTime endDate) {
            object[] results = this.Invoke("GetPostings", new object[] {
                        authHeader,
                        myDay,
                        startDate,
                        endDate});
            return ((Posting[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPostingsAsync(AuthenticationHeader authHeader, bool myDay, System.DateTime startDate, System.DateTime endDate) {
            this.GetPostingsAsync(authHeader, myDay, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void GetPostingsAsync(AuthenticationHeader authHeader, bool myDay, System.DateTime startDate, System.DateTime endDate, object userState) {
            if ((this.GetPostingsOperationCompleted == null)) {
                this.GetPostingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPostingsOperationCompleted);
            }
            this.InvokeAsync("GetPostings", new object[] {
                        authHeader,
                        myDay,
                        startDate,
                        endDate}, this.GetPostingsOperationCompleted, userState);
        }
        
        private void OnGetPostingsOperationCompleted(object arg) {
            if ((this.GetPostingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPostingsCompleted(this, new GetPostingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/UpdatePo" +
            "stings", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] UpdatePostings(AuthenticationHeader authHeader, UpdatedPosting[] updatedPostings) {
            object[] results = this.Invoke("UpdatePostings", new object[] {
                        authHeader,
                        updatedPostings});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePostingsAsync(AuthenticationHeader authHeader, UpdatedPosting[] updatedPostings) {
            this.UpdatePostingsAsync(authHeader, updatedPostings, null);
        }
        
        /// <remarks/>
        public void UpdatePostingsAsync(AuthenticationHeader authHeader, UpdatedPosting[] updatedPostings, object userState) {
            if ((this.UpdatePostingsOperationCompleted == null)) {
                this.UpdatePostingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePostingsOperationCompleted);
            }
            this.InvokeAsync("UpdatePostings", new object[] {
                        authHeader,
                        updatedPostings}, this.UpdatePostingsOperationCompleted, userState);
        }
        
        private void OnUpdatePostingsOperationCompleted(object arg) {
            if ((this.UpdatePostingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePostingsCompleted(this, new UpdatePostingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/AddDevic" +
            "eToken", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddDeviceToken(string token, string Username, string activate) {
            object[] results = this.Invoke("AddDeviceToken", new object[] {
                        token,
                        Username,
                        activate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddDeviceTokenAsync(string token, string Username, string activate) {
            this.AddDeviceTokenAsync(token, Username, activate, null);
        }
        
        /// <remarks/>
        public void AddDeviceTokenAsync(string token, string Username, string activate, object userState) {
            if ((this.AddDeviceTokenOperationCompleted == null)) {
                this.AddDeviceTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddDeviceTokenOperationCompleted);
            }
            this.InvokeAsync("AddDeviceToken", new object[] {
                        token,
                        Username,
                        activate}, this.AddDeviceTokenOperationCompleted, userState);
        }
        
        private void OnAddDeviceTokenOperationCompleted(object arg) {
            if ((this.AddDeviceTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddDeviceTokenCompleted(this, new AddDeviceTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/SendPush" +
            "Alert", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendPushAlert(string agentUserId, string message, out string error) {
            object[] results = this.Invoke("SendPushAlert", new object[] {
                        agentUserId,
                        message});
            error = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendPushAlertAsync(string agentUserId, string message) {
            this.SendPushAlertAsync(agentUserId, message, null);
        }
        
        /// <remarks/>
        public void SendPushAlertAsync(string agentUserId, string message, object userState) {
            if ((this.SendPushAlertOperationCompleted == null)) {
                this.SendPushAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPushAlertOperationCompleted);
            }
            this.InvokeAsync("SendPushAlert", new object[] {
                        agentUserId,
                        message}, this.SendPushAlertOperationCompleted, userState);
        }
        
        private void OnSendPushAlertOperationCompleted(object arg) {
            if ((this.SendPushAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendPushAlertCompleted(this, new SendPushAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/GetAgent" +
            "OrDelegateByOrderId", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAgentOrDelegateByOrderId(int asapId) {
            object[] results = this.Invoke("GetAgentOrDelegateByOrderId", new object[] {
                        asapId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgentOrDelegateByOrderIdAsync(int asapId) {
            this.GetAgentOrDelegateByOrderIdAsync(asapId, null);
        }
        
        /// <remarks/>
        public void GetAgentOrDelegateByOrderIdAsync(int asapId, object userState) {
            if ((this.GetAgentOrDelegateByOrderIdOperationCompleted == null)) {
                this.GetAgentOrDelegateByOrderIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgentOrDelegateByOrderIdOperationCompleted);
            }
            this.InvokeAsync("GetAgentOrDelegateByOrderId", new object[] {
                        asapId}, this.GetAgentOrDelegateByOrderIdOperationCompleted, userState);
        }
        
        private void OnGetAgentOrDelegateByOrderIdOperationCompleted(object arg) {
            if ((this.GetAgentOrDelegateByOrderIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgentOrDelegateByOrderIdCompleted(this, new GetAgentOrDelegateByOrderIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/GetOrder" +
            "ById", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sales[] GetOrderById(AuthenticationHeader authHeader, string asapId) {
            object[] results = this.Invoke("GetOrderById", new object[] {
                        authHeader,
                        asapId});
            return ((Sales[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderByIdAsync(AuthenticationHeader authHeader, string asapId) {
            this.GetOrderByIdAsync(authHeader, asapId, null);
        }
        
        /// <remarks/>
        public void GetOrderByIdAsync(AuthenticationHeader authHeader, string asapId, object userState) {
            if ((this.GetOrderByIdOperationCompleted == null)) {
                this.GetOrderByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderByIdOperationCompleted);
            }
            this.InvokeAsync("GetOrderById", new object[] {
                        authHeader,
                        asapId}, this.GetOrderByIdOperationCompleted, userState);
        }
        
        private void OnGetOrderByIdOperationCompleted(object arg) {
            if ((this.GetOrderByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderByIdCompleted(this, new GetOrderByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/GetSales" +
            "", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sales[] GetSales(AuthenticationHeader authHeader, string agentUserId) {
            object[] results = this.Invoke("GetSales", new object[] {
                        authHeader,
                        agentUserId});
            return ((Sales[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSalesAsync(AuthenticationHeader authHeader, string agentUserId) {
            this.GetSalesAsync(authHeader, agentUserId, null);
        }
        
        /// <remarks/>
        public void GetSalesAsync(AuthenticationHeader authHeader, string agentUserId, object userState) {
            if ((this.GetSalesOperationCompleted == null)) {
                this.GetSalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesOperationCompleted);
            }
            this.InvokeAsync("GetSales", new object[] {
                        authHeader,
                        agentUserId}, this.GetSalesOperationCompleted, userState);
        }
        
        private void OnGetSalesOperationCompleted(object arg) {
            if ((this.GetSalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesCompleted(this, new GetSalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/UpdateSa" +
            "les", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sales[] UpdateSales(AuthenticationHeader authHeader, SaleResult[] SaleResults) {
            object[] results = this.Invoke("UpdateSales", new object[] {
                        authHeader,
                        SaleResults});
            return ((Sales[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSalesAsync(AuthenticationHeader authHeader, SaleResult[] SaleResults) {
            this.UpdateSalesAsync(authHeader, SaleResults, null);
        }
        
        /// <remarks/>
        public void UpdateSalesAsync(AuthenticationHeader authHeader, SaleResult[] SaleResults, object userState) {
            if ((this.UpdateSalesOperationCompleted == null)) {
                this.UpdateSalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSalesOperationCompleted);
            }
            this.InvokeAsync("UpdateSales", new object[] {
                        authHeader,
                        SaleResults}, this.UpdateSalesOperationCompleted, userState);
        }
        
        private void OnUpdateSalesOperationCompleted(object arg) {
            if ((this.UpdateSalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSalesCompleted(this, new UpdateSalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/ConfirmC" +
            "anXPPT", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ConfirmCanXPPT(AuthenticationHeader authHeader, SaleResult[] SaleResults) {
            object[] results = this.Invoke("ConfirmCanXPPT", new object[] {
                        authHeader,
                        SaleResults});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmCanXPPTAsync(AuthenticationHeader authHeader, SaleResult[] SaleResults) {
            this.ConfirmCanXPPTAsync(authHeader, SaleResults, null);
        }
        
        /// <remarks/>
        public void ConfirmCanXPPTAsync(AuthenticationHeader authHeader, SaleResult[] SaleResults, object userState) {
            if ((this.ConfirmCanXPPTOperationCompleted == null)) {
                this.ConfirmCanXPPTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmCanXPPTOperationCompleted);
            }
            this.InvokeAsync("ConfirmCanXPPT", new object[] {
                        authHeader,
                        SaleResults}, this.ConfirmCanXPPTOperationCompleted, userState);
        }
        
        private void OnConfirmCanXPPTOperationCompleted(object arg) {
            if ((this.ConfirmCanXPPTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmCanXPPTCompleted(this, new ConfirmCanXPPTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx/UpdateHo" +
            "ld", RequestNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", ResponseNamespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateHold(AuthenticationHeader authHeader, string asapId) {
            object[] results = this.Invoke("UpdateHold", new object[] {
                        authHeader,
                        asapId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateHoldAsync(AuthenticationHeader authHeader, string asapId) {
            this.UpdateHoldAsync(authHeader, asapId, null);
        }
        
        /// <remarks/>
        public void UpdateHoldAsync(AuthenticationHeader authHeader, string asapId, object userState) {
            if ((this.UpdateHoldOperationCompleted == null)) {
                this.UpdateHoldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateHoldOperationCompleted);
            }
            this.InvokeAsync("UpdateHold", new object[] {
                        authHeader,
                        asapId}, this.UpdateHoldOperationCompleted, userState);
        }
        
        private void OnUpdateHoldOperationCompleted(object arg) {
            if ((this.UpdateHoldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateHoldCompleted(this, new UpdateHoldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx")]
    public partial class AuthenticationHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private string deviceidField;
        
        private string versionField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Deviceid {
            get {
                return this.deviceidField;
            }
            set {
                this.deviceidField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx")]
    public partial class SaleResult {
        
        private string orderIdField;
        
        private string soldAmountField;
        
        private string saleResultIDField;
        
        private string representativeField;
        
        private string vestedToNameField;
        
        private string vestedAsField;
        
        private string vestingNotesField;
        
        private string sendToStreetField;
        
        private string sendToStateField;
        
        private string sendToZipField;
        
        private string sendToPhoneField;
        
        private string sendToCityField;
        
        private string saleNumberPresentField;
        
        private string saleNumberInterestedField;
        
        private string saleCompletedDateField;
        
        private string saleInfoCompletedAtField;
        
        private string lastUpdateDateField;
        
        private ImageData[] imagesField;
        
        /// <remarks/>
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public string SoldAmount {
            get {
                return this.soldAmountField;
            }
            set {
                this.soldAmountField = value;
            }
        }
        
        /// <remarks/>
        public string SaleResultID {
            get {
                return this.saleResultIDField;
            }
            set {
                this.saleResultIDField = value;
            }
        }
        
        /// <remarks/>
        public string Representative {
            get {
                return this.representativeField;
            }
            set {
                this.representativeField = value;
            }
        }
        
        /// <remarks/>
        public string VestedToName {
            get {
                return this.vestedToNameField;
            }
            set {
                this.vestedToNameField = value;
            }
        }
        
        /// <remarks/>
        public string VestedAs {
            get {
                return this.vestedAsField;
            }
            set {
                this.vestedAsField = value;
            }
        }
        
        /// <remarks/>
        public string VestingNotes {
            get {
                return this.vestingNotesField;
            }
            set {
                this.vestingNotesField = value;
            }
        }
        
        /// <remarks/>
        public string SendToStreet {
            get {
                return this.sendToStreetField;
            }
            set {
                this.sendToStreetField = value;
            }
        }
        
        /// <remarks/>
        public string SendToState {
            get {
                return this.sendToStateField;
            }
            set {
                this.sendToStateField = value;
            }
        }
        
        /// <remarks/>
        public string SendToZip {
            get {
                return this.sendToZipField;
            }
            set {
                this.sendToZipField = value;
            }
        }
        
        /// <remarks/>
        public string SendToPhone {
            get {
                return this.sendToPhoneField;
            }
            set {
                this.sendToPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string SendToCity {
            get {
                return this.sendToCityField;
            }
            set {
                this.sendToCityField = value;
            }
        }
        
        /// <remarks/>
        public string SaleNumberPresent {
            get {
                return this.saleNumberPresentField;
            }
            set {
                this.saleNumberPresentField = value;
            }
        }
        
        /// <remarks/>
        public string SaleNumberInterested {
            get {
                return this.saleNumberInterestedField;
            }
            set {
                this.saleNumberInterestedField = value;
            }
        }
        
        /// <remarks/>
        public string SaleCompletedDate {
            get {
                return this.saleCompletedDateField;
            }
            set {
                this.saleCompletedDateField = value;
            }
        }
        
        /// <remarks/>
        public string SaleInfoCompletedAt {
            get {
                return this.saleInfoCompletedAtField;
            }
            set {
                this.saleInfoCompletedAtField = value;
            }
        }
        
        /// <remarks/>
        public string LastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                this.lastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        public ImageData[] Images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx")]
    public partial class ImageData {
        
        private string dataField;
        
        private System.DateTime dateCreatedField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx")]
    public partial class Sales {
        
        private string aSAPIDField;
        
        private string tSNumField;
        
        private string clientIDField;
        
        private string clientNumField;
        
        private string aPNField;
        
        private string trustorField;
        
        private string saleDateTimeField;
        
        private string locationNameField;
        
        private string pPTFromDateField;
        
        private string pPTToDateField;
        
        private string pPTReasonField;
        
        private string noticeOfSaleAmtField;
        
        private string openLowField;
        
        private string openHighField;
        
        private string propertyClearIndField;
        
        private string incrementField;
        
        private string stateField;
        
        private string propertyStreetField;
        
        private string propertyCityField;
        
        private string propertyZipField;
        
        private string countyIDField;
        
        private string currentStatusField;
        
        private string soldResultField;
        
        private string bidAtIndField;
        
        private string bidTypeField;
        
        private string saleLocatonGMTOffSetField;
        
        private string agentNameField;
        
        private string instrumentField;
        
        private string bookField;
        
        private string pageField;
        
        private string recordedDateField;
        
        private string notesField;
        
        private string soldAmountField;
        
        private string saleResultIDField;
        
        private string representativeField;
        
        private string vestedToNameField;
        
        private string vestedAsField;
        
        private string vestingNotesField;
        
        private string sendToStreetField;
        
        private string sendToStateField;
        
        private string sendToZipField;
        
        private string sendToPhoneField;
        
        private string sendToCityField;
        
        private string saleNumberPresentField;
        
        private string saleNumberInterestedField;
        
        private string saleCompletedDateField;
        
        private string saleInfoCompletedAtField;
        
        private string lastUpdateDateField;
        
        /// <remarks/>
        public string ASAPID {
            get {
                return this.aSAPIDField;
            }
            set {
                this.aSAPIDField = value;
            }
        }
        
        /// <remarks/>
        public string TSNum {
            get {
                return this.tSNumField;
            }
            set {
                this.tSNumField = value;
            }
        }
        
        /// <remarks/>
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        public string ClientNum {
            get {
                return this.clientNumField;
            }
            set {
                this.clientNumField = value;
            }
        }
        
        /// <remarks/>
        public string APN {
            get {
                return this.aPNField;
            }
            set {
                this.aPNField = value;
            }
        }
        
        /// <remarks/>
        public string Trustor {
            get {
                return this.trustorField;
            }
            set {
                this.trustorField = value;
            }
        }
        
        /// <remarks/>
        public string SaleDateTime {
            get {
                return this.saleDateTimeField;
            }
            set {
                this.saleDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        public string PPTFromDate {
            get {
                return this.pPTFromDateField;
            }
            set {
                this.pPTFromDateField = value;
            }
        }
        
        /// <remarks/>
        public string PPTToDate {
            get {
                return this.pPTToDateField;
            }
            set {
                this.pPTToDateField = value;
            }
        }
        
        /// <remarks/>
        public string PPTReason {
            get {
                return this.pPTReasonField;
            }
            set {
                this.pPTReasonField = value;
            }
        }
        
        /// <remarks/>
        public string NoticeOfSaleAmt {
            get {
                return this.noticeOfSaleAmtField;
            }
            set {
                this.noticeOfSaleAmtField = value;
            }
        }
        
        /// <remarks/>
        public string OpenLow {
            get {
                return this.openLowField;
            }
            set {
                this.openLowField = value;
            }
        }
        
        /// <remarks/>
        public string OpenHigh {
            get {
                return this.openHighField;
            }
            set {
                this.openHighField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyClearInd {
            get {
                return this.propertyClearIndField;
            }
            set {
                this.propertyClearIndField = value;
            }
        }
        
        /// <remarks/>
        public string Increment {
            get {
                return this.incrementField;
            }
            set {
                this.incrementField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyStreet {
            get {
                return this.propertyStreetField;
            }
            set {
                this.propertyStreetField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyCity {
            get {
                return this.propertyCityField;
            }
            set {
                this.propertyCityField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyZip {
            get {
                return this.propertyZipField;
            }
            set {
                this.propertyZipField = value;
            }
        }
        
        /// <remarks/>
        public string CountyID {
            get {
                return this.countyIDField;
            }
            set {
                this.countyIDField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentStatus {
            get {
                return this.currentStatusField;
            }
            set {
                this.currentStatusField = value;
            }
        }
        
        /// <remarks/>
        public string SoldResult {
            get {
                return this.soldResultField;
            }
            set {
                this.soldResultField = value;
            }
        }
        
        /// <remarks/>
        public string BidAtInd {
            get {
                return this.bidAtIndField;
            }
            set {
                this.bidAtIndField = value;
            }
        }
        
        /// <remarks/>
        public string BidType {
            get {
                return this.bidTypeField;
            }
            set {
                this.bidTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SaleLocatonGMTOffSet {
            get {
                return this.saleLocatonGMTOffSetField;
            }
            set {
                this.saleLocatonGMTOffSetField = value;
            }
        }
        
        /// <remarks/>
        public string AgentName {
            get {
                return this.agentNameField;
            }
            set {
                this.agentNameField = value;
            }
        }
        
        /// <remarks/>
        public string Instrument {
            get {
                return this.instrumentField;
            }
            set {
                this.instrumentField = value;
            }
        }
        
        /// <remarks/>
        public string Book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
            }
        }
        
        /// <remarks/>
        public string Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        public string RecordedDate {
            get {
                return this.recordedDateField;
            }
            set {
                this.recordedDateField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public string SoldAmount {
            get {
                return this.soldAmountField;
            }
            set {
                this.soldAmountField = value;
            }
        }
        
        /// <remarks/>
        public string SaleResultID {
            get {
                return this.saleResultIDField;
            }
            set {
                this.saleResultIDField = value;
            }
        }
        
        /// <remarks/>
        public string Representative {
            get {
                return this.representativeField;
            }
            set {
                this.representativeField = value;
            }
        }
        
        /// <remarks/>
        public string VestedToName {
            get {
                return this.vestedToNameField;
            }
            set {
                this.vestedToNameField = value;
            }
        }
        
        /// <remarks/>
        public string VestedAs {
            get {
                return this.vestedAsField;
            }
            set {
                this.vestedAsField = value;
            }
        }
        
        /// <remarks/>
        public string VestingNotes {
            get {
                return this.vestingNotesField;
            }
            set {
                this.vestingNotesField = value;
            }
        }
        
        /// <remarks/>
        public string SendToStreet {
            get {
                return this.sendToStreetField;
            }
            set {
                this.sendToStreetField = value;
            }
        }
        
        /// <remarks/>
        public string SendToState {
            get {
                return this.sendToStateField;
            }
            set {
                this.sendToStateField = value;
            }
        }
        
        /// <remarks/>
        public string SendToZip {
            get {
                return this.sendToZipField;
            }
            set {
                this.sendToZipField = value;
            }
        }
        
        /// <remarks/>
        public string SendToPhone {
            get {
                return this.sendToPhoneField;
            }
            set {
                this.sendToPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string SendToCity {
            get {
                return this.sendToCityField;
            }
            set {
                this.sendToCityField = value;
            }
        }
        
        /// <remarks/>
        public string SaleNumberPresent {
            get {
                return this.saleNumberPresentField;
            }
            set {
                this.saleNumberPresentField = value;
            }
        }
        
        /// <remarks/>
        public string SaleNumberInterested {
            get {
                return this.saleNumberInterestedField;
            }
            set {
                this.saleNumberInterestedField = value;
            }
        }
        
        /// <remarks/>
        public string SaleCompletedDate {
            get {
                return this.saleCompletedDateField;
            }
            set {
                this.saleCompletedDateField = value;
            }
        }
        
        /// <remarks/>
        public string SaleInfoCompletedAt {
            get {
                return this.saleInfoCompletedAtField;
            }
            set {
                this.saleInfoCompletedAtField = value;
            }
        }
        
        /// <remarks/>
        public string LastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                this.lastUpdateDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx")]
    public partial class UpdatedPosting {
        
        private string orderIdField;
        
        private string occupancyField;
        
        private bool occupantContactedField;
        
        private string areaTypeField;
        
        private string postedOnField;
        
        private int numPostingsField;
        
        private string forSaleByField;
        
        private bool forSaleSignField;
        
        private string commentsField;
        
        private System.DateTime savedTimeStampField;
        
        private bool isRepostingField;
        
        private bool isExceptionField;
        
        private string exceptionReasonField;
        
        private bool isNorField;
        
        private ImageData[] imagesField;
        
        /// <remarks/>
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public string Occupancy {
            get {
                return this.occupancyField;
            }
            set {
                this.occupancyField = value;
            }
        }
        
        /// <remarks/>
        public bool OccupantContacted {
            get {
                return this.occupantContactedField;
            }
            set {
                this.occupantContactedField = value;
            }
        }
        
        /// <remarks/>
        public string AreaType {
            get {
                return this.areaTypeField;
            }
            set {
                this.areaTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PostedOn {
            get {
                return this.postedOnField;
            }
            set {
                this.postedOnField = value;
            }
        }
        
        /// <remarks/>
        public int NumPostings {
            get {
                return this.numPostingsField;
            }
            set {
                this.numPostingsField = value;
            }
        }
        
        /// <remarks/>
        public string ForSaleBy {
            get {
                return this.forSaleByField;
            }
            set {
                this.forSaleByField = value;
            }
        }
        
        /// <remarks/>
        public bool ForSaleSign {
            get {
                return this.forSaleSignField;
            }
            set {
                this.forSaleSignField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SavedTimeStamp {
            get {
                return this.savedTimeStampField;
            }
            set {
                this.savedTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public bool IsReposting {
            get {
                return this.isRepostingField;
            }
            set {
                this.isRepostingField = value;
            }
        }
        
        /// <remarks/>
        public bool IsException {
            get {
                return this.isExceptionField;
            }
            set {
                this.isExceptionField = value;
            }
        }
        
        /// <remarks/>
        public string ExceptionReason {
            get {
                return this.exceptionReasonField;
            }
            set {
                this.exceptionReasonField = value;
            }
        }
        
        /// <remarks/>
        public bool IsNor {
            get {
                return this.isNorField;
            }
            set {
                this.isNorField = value;
            }
        }
        
        /// <remarks/>
        public ImageData[] Images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx")]
    public partial class Posting {
        
        private string orderIdField;
        
        private string tSNumberField;
        
        private string clientNumField;
        
        private string trustorField;
        
        private string propertyAddressField;
        
        private string propertyStateField;
        
        private string propertyCountyField;
        
        private string propertyCityField;
        
        private string propertyZipField;
        
        private System.DateTime saleDateTimeField;
        
        private System.DateTime firstPubDateField;
        
        private System.DateTime postByDateField;
        
        private bool postOnField;
        
        private System.DateTime datedDateField;
        
        private string postTypeField;
        
        private string aPNField;
        
        private string postNotesField;
        
        private bool cancelIndField;
        
        private bool isPostingRejectedField;
        
        private bool completedField;
        
        /// <remarks/>
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public string TSNumber {
            get {
                return this.tSNumberField;
            }
            set {
                this.tSNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ClientNum {
            get {
                return this.clientNumField;
            }
            set {
                this.clientNumField = value;
            }
        }
        
        /// <remarks/>
        public string Trustor {
            get {
                return this.trustorField;
            }
            set {
                this.trustorField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyAddress {
            get {
                return this.propertyAddressField;
            }
            set {
                this.propertyAddressField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyState {
            get {
                return this.propertyStateField;
            }
            set {
                this.propertyStateField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyCounty {
            get {
                return this.propertyCountyField;
            }
            set {
                this.propertyCountyField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyCity {
            get {
                return this.propertyCityField;
            }
            set {
                this.propertyCityField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyZip {
            get {
                return this.propertyZipField;
            }
            set {
                this.propertyZipField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SaleDateTime {
            get {
                return this.saleDateTimeField;
            }
            set {
                this.saleDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FirstPubDate {
            get {
                return this.firstPubDateField;
            }
            set {
                this.firstPubDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PostByDate {
            get {
                return this.postByDateField;
            }
            set {
                this.postByDateField = value;
            }
        }
        
        /// <remarks/>
        public bool PostOn {
            get {
                return this.postOnField;
            }
            set {
                this.postOnField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatedDate {
            get {
                return this.datedDateField;
            }
            set {
                this.datedDateField = value;
            }
        }
        
        /// <remarks/>
        public string PostType {
            get {
                return this.postTypeField;
            }
            set {
                this.postTypeField = value;
            }
        }
        
        /// <remarks/>
        public string APN {
            get {
                return this.aPNField;
            }
            set {
                this.aPNField = value;
            }
        }
        
        /// <remarks/>
        public string PostNotes {
            get {
                return this.postNotesField;
            }
            set {
                this.postNotesField = value;
            }
        }
        
        /// <remarks/>
        public bool CancelInd {
            get {
                return this.cancelIndField;
            }
            set {
                this.cancelIndField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPostingRejected {
            get {
                return this.isPostingRejectedField;
            }
            set {
                this.isPostingRejectedField = value;
            }
        }
        
        /// <remarks/>
        public bool Completed {
            get {
                return this.completedField;
            }
            set {
                this.completedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx")]
    public partial class Signature {
        
        private string signatureDataField;
        
        /// <remarks/>
        public string SignatureData {
            get {
                return this.signatureDataField;
            }
            set {
                this.signatureDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://staging.wise.servicelinkasap.com/fieldservices/fieldservice.asmx")]
    public partial class User {
        
        private string agentUserIDField;
        
        private string passwordField;
        
        private string pwdExpiredField;
        
        private string forgotPwdField;
        
        /// <remarks/>
        public string agentUserID {
            get {
                return this.agentUserIDField;
            }
            set {
                this.agentUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string pwdExpired {
            get {
                return this.pwdExpiredField;
            }
            set {
                this.pwdExpiredField = value;
            }
        }
        
        /// <remarks/>
        public string forgotPwd {
            get {
                return this.forgotPwdField;
            }
            set {
                this.forgotPwdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AuthenticateUserCompletedEventHandler(object sender, AuthenticateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AuthenticateDeviceCompletedEventHandler(object sender, AuthenticateDeviceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateDeviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateDeviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateSignatureCompletedEventHandler(object sender, UpdateSignatureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSignatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSignatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPostingsCompletedEventHandler(object sender, GetPostingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPostingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPostingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Posting[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Posting[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdatePostingsCompletedEventHandler(object sender, UpdatePostingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePostingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePostingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AddDeviceTokenCompletedEventHandler(object sender, AddDeviceTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddDeviceTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddDeviceTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendPushAlertCompletedEventHandler(object sender, SendPushAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendPushAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendPushAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAgentOrDelegateByOrderIdCompletedEventHandler(object sender, GetAgentOrDelegateByOrderIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgentOrDelegateByOrderIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgentOrDelegateByOrderIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetOrderByIdCompletedEventHandler(object sender, GetOrderByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sales[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sales[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSalesCompletedEventHandler(object sender, GetSalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sales[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sales[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateSalesCompletedEventHandler(object sender, UpdateSalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sales[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sales[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ConfirmCanXPPTCompletedEventHandler(object sender, ConfirmCanXPPTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmCanXPPTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmCanXPPTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateHoldCompletedEventHandler(object sender, UpdateHoldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateHoldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateHoldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591